apiVersion: apps/v1
kind: Deployment
metadata:
  name: direct-offline-deploy
  namespace: bots
  labels:
    app: direct-offline-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: direct-offline-app
  template:
    metadata:
      labels:
        app: direct-offline-app
    spec:
      containers:
      - name: direct-offline-app
        image: __ACR_NAME__.azurecr.io/direct-offline:latest
        ports:
        - containerPort: 3000
        env:
        - name: BOT_URL
          value: http://cqabot-svc.bots.svc.cluster.local:3978/api/messages
        - name: DIRECTLINE_DOMAIN
          value: __IP__
